src/Entity/Formateur.php
<?php

namespace App\Entity;

use App\Repository\FormateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormateurRepository::class)]
class Formateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\OneToMany(mappedBy: 'formateur', targetEntity: Session::class)]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setFormateur($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getFormateur() === $this) {
                $session->setFormateur(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->getPrenom().' '.$this->getNom();
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Places = null;

    #[ORM\Column(length: 255)]
    private ?string $intitule = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fin = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formateur $formateur = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $formation = null;

    #[ORM\ManyToMany(targetEntity: Stagiaire::class, inversedBy: 'sessions')]
    private Collection $stagiaires;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: Programme::class, orphanRemoval: true)]
    private Collection $programmes;

    #[ORM\OneToMany(mappedBy: 'session', targetEntity: Utiliser::class, orphanRemoval: true)]
    private Collection $utilisers;

    public function __construct()
    {
        $this->stagiaires = new ArrayCollection();
        $this->programmes = new ArrayCollection();
        $this->utilisers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlaces(): ?int
    {
        return $this->Places;
    }

    public function setPlaces(int $Places): static
    {
        $this->Places = $Places;

        return $this;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): static
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDebut(): ?\DateTimeInterface
    {
        return $this->debut;
    }

    public function setDebut(\DateTimeInterface $debut): static
    {
        $this->debut = $debut;

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(\DateTimeInterface $fin): static
    {
        $this->fin = $fin;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->add($stagiaire);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        $this->stagiaires->removeElement($stagiaire);

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->intitule;
    }

    /**
     * @return Collection<int, Utiliser>
     */
    public function getUtilisers(): Collection
    {
        return $this->utilisers;
    }

    public function addUtiliser(Utiliser $utiliser): static
    {
        if (!$this->utilisers->contains($utiliser)) {
            $this->utilisers->add($utiliser);
            $utiliser->setSession($this);
        }

        return $this;
    }

    public function removeUtiliser(Utiliser $utiliser): static
    {
        if ($this->utilisers->removeElement($utiliser)) {
            // set the owning side to null (unless already changed)
            if ($utiliser->getSession() === $this) {
                $utiliser->setSession(null);
            }
        }

        return $this;
    }
}

src/Form/FormateurType.php
<?php

namespace App\Form;

use App\Entity\Formateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class FormateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('Valider', SubmitType::class) 
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formateur::class,
        ]);
    }
}

src/Controller/FormateurController.php
<?php

namespace App\Controller;

use App\Entity\Formateur;
use App\Form\FormateurType;
use App\Repository\FormateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FormateurController extends AbstractController
{
    #[Route('/formateur', name: 'app_formateur')]
    public function index(FormateurRepository $fr): Response
    {
        return $this->render('formateur/index.html.twig', [
            'formateurs'=>$fr->findAll()
        ]);
    }

    #[Route('/formateur/new', name: 'new_formateur')]
    #[Route('/formateur/{id}/edit', name: 'edit_formateur')] // si on veux rajouter l'edition 
    public function new_edit(Formateur $formateur =null ,Request $request , EntityManagerInterface $entityManager):Response {

	if(!$formateur ){$formateur = new Formateur();} //////////// crée une nouvelle formateur ( un objet pas dans la bdd ) } // si on veux rajouter l'edition sinon on enleve le if mais on garde l'interrieur
        
        $form = $this->createForm(FormateurType::class, $formateur); ////// ( crée le formulaire )

 	$form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() ){ // si le form est submit et qu'il est valide
            $formateur = $form->getData(); //on met les info dans l'entité formateur crée plus haut  
            $entityManager->persist($formateur); // prepare en pdo 
            $entityManager->flush(); // execute en pdo
            $this->addFlash("success","ajout du formateur avec succes");
            return $this->redirectToRoute('app_formateur');
        }


        return $this->render('formateur/new.html.twig',[  //////// ( envoie du form dans la vue ) 
            'FormAddFormateur'=> $form  ,
        ]);
    } 
    #[Route('/formateur/{id}/delete', name: 'delete_formateur')]
    public function delete(Formateur $formateur , EntityManagerInterface $em){   
        $em->remove($formateur);
        $em->flush();
        $this->addFlash("success","suppression du formateur avec succes");
        return $this->redirectToRoute('app_formateur');
    }


    #[Route('/formateur/{id}', name: 'show_formateur')]
    public function show(Formateur $formateur , FormateurRepository $fr): Response
    {   
        
        return $this->render('formateur/show.html.twig', [
            'formateur'=>$fr->find($formateur->getId())
        ]);
    }
}

templates/formateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}liste des formateurs{% endblock %}

{% block body %}
<h1 class="subtitle">Liste des formateurs</h1>
<div  class="table_btn_wrapper">
    <table class="styled-table">
        <thead>
            <tr>
                <th>Nom Prenom</th>
                <th>a encadré</th>
                <th>Encardre</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% set currentDate = "now"|date('Y-m-d') %}
            {% for formateur in formateurs %}

            {% set x = 0 %}
            {% for session in formateur.sessions %}
        
            
                {% if session.fin|date('Y-m-d') >= currentDate|date('Y-m-d') and session.debut|date('Y-m-d') <= currentDate|date('Y-m-d') %}

                    {% set x = x + 1 %}
                    
                {% endif %}
            {% endfor %}
            <tr>
                <td class="intitule"><a title="info formateur" href="{{path('show_formateur',{'id':formateur.id})}}">{{formateur.nom}} {{formateur.prenom}}</a> </td>
                
                <td>{{formateur.sessions|length}}</td>
                
                <td>{{x}}</td>

                <td><a title="modifier ce formateur" style="color:orange" href="{{path('edit_formateur',{'id':formateur.id})}}"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a title="supprimer ce formateur" style="color:red" href="{{path('delete_formateur',{'id':formateur.id})}}"><i class="fa-solid fa-x"></i></a></td>
               
            </tr>
        
            {% endfor %}
        <tbody>
    </table>
    <br>
    <a title="ajouter un formateur" class="addBtn" href="{{path('new_formateur')}}">Ajouter</a>
</div>


{% endblock %}
    

templates/formateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un formateur{% endblock %}

{% block body %}

    <h1 class="subtitle">Ajouter un Formateur</h1>
    
    {{ form_start(FormAddFormateur, {'attr': {'class': 'form_session'}}) }}
    
        {{form_row(FormAddFormateur.nom)}}
        {{form_row(FormAddFormateur.prenom)}}
       
   
    {{form_end(FormAddFormateur) }}
    

{% endblock %}

templates/formateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{formateur.nom}} {{formateur.prenom}} {% endblock %}


{% block body %}

<h1 class="subtitle">liste des sessions encadrés par "{{formateur.nom}} {{formateur.prenom}}"</h1>

<table class="styled-table center">
    <thead>
        <tr>
            <th>Intitulé Session</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Inscrits</th>
            <th>Actions</th>
        
        </tr>
    </thead>
    <tbody>
        {% for session in formateur.sessions %}
        <tr>
            <td class="intitule"><a title="info session" href=" {{path('show_session',{'id':session.id}) }} ">{{session.Intitule}} </a></td>
            <td>{{session.debut|date('d-m-Y')}}</td>
            <td>{{session.fin|date('d-m-Y')}}</td>
            <td>{{session.stagiaires | length}} / {{session.places}}</td>
            
        
            <td><a title="modifier session" style="color:orange" href="{{path('edit_session',{'id':session.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a>
            <a title="annuler session" style="color:red" href="{{path('delete_session',{'id':session.id}) }}"><i class="fa-solid fa-x"></i></a></td>
        </tr>
    
        {% endfor %}
    <tbody>
</table>




{% endblock %}